box_content:
  type: markdown
  name: Box content
  content: 
        <h1>The box</h1>
        <p><strong>Pellentesque habitant morbi tristique</strong> senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.</em>. Vestibulum erat wisi, condimentum sed, <code>commodo vitae</code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href="#">Donec non enim</a> in turpis pulvinar facilisis. Ut felis.</p>
        <h2>Just CSS playground</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi, nihil perferendis dolores. Aliquid, provident, aperiam, ut tempore nostrum sed accusamus qui id libero soluta dolore esse molestias quibusdam non suscipit!</p>
  help: This is your content area. You can use Markdown syntax. 
css_style:
  type: css
  name: Custom css
  help: Customize your box with custom CSS.
